### ISSUE TITLE
Make hardcoded dependency to spray-client version configurable

### ISSUE THREAD

**Issue by magnusart** [sclasen/spray-aws#1]
Hi

The line below makes it very hard to use any other version than 1.1-M7 of the spray library whilst using spray-dynamodb with evetsourced.

https://github.com/sclasen/spray-aws/blob/master/spray-aws/src/main/scala/com/sclasen/spray/aws/SprayAWSClient.scala#L77

There is a nasty bug nasty bug in spray-routes in 1.1-M7 that I also use, but when I upgrade to a nightly build where the bug is fixed, SBT evicts spray-client and replaces with a newer version for dynamo-journal as well. That of course leads to runtime errors when communicating with AWS.

**Comment by sclasen** [comment]
Aha yes nice catch, will get that updated and released, and also have eventsourced updated

**Comment by sclasen** [comment]
@magnusart just pushed 0.1.3-SNAPSHOT to oss.sonaytpe.org, should pull the proper value out of spray client settings now.

do you want to try excluding 0.1.2 from your eventsourced-journal-dynamodb dependency and add spray-aws and spray-dynamodb 0.1.3-SNAPSHOT to you deps?

If this works as expected, Ill cut a release to maven central and get eventsourced updated.

Thanks!

**Comment by magnusart** [comment]
Absolutely, it's getting late over here but I'll give it a go first thing in the morning!

**Comment by magnusart** [comment]
Hi again. It works as expected with 1.1-M7. So I'd say the issue with hard coding is resolved.

However in the later snapshot of spray-can I tried out using, ClientSettings object have been renamed to ClientConnectionSettings so I get a class not found exception. 

Not much do do there from the perspective of spray-aws, but to wait for a major release. There will probably need to be some adjustments to make spray-aws/dynamodb work properly with that version. 

When using the snapshot there seems like there are a lot of changes and renames are coming in Spray that would warrant a new minor, if not major, release number.
