### ISSUE TITLE
Possible issue with formData

### ISSUE THREAD

**Issue by slomo** [sclasen/spray-aws#7]
I am trying to get the S3 api integrated in my [own branch](https://github.com/fidesmo/spray-aws/tree/s3-multi-delete).

To implement the [multi objects delete](http://docs.aws.amazon.com/AmazonS3/latest/API/multiobjectdeleteapi.html), I need to send a request with formData and content, which is done by using content-type multipart/form-data. As a result I have been running into issues with the x-amz-content-sha256 which now doesn't fit since I altered the body part of the request ( see current non-working [implementation](https://github.com/fidesmo/spray-aws/blob/932dc117a82be9787cc03f293eed811da58e9b29/spray-aws/src/main/scala/com/sclasen/spray/aws/SprayAWSClient.scala#L120)).

Taking a deeper look at the AWS4Signer I am now kind of confused how the actual signing of requests with formData works in spray-aws. Because the signer seems to exclude the request parameters from the signature for POST and PUT (see [aws-jdk-java](https://github.com/aws/aws-sdk-java/blob/master/src/main/java/com/amazonaws/auth/AbstractAWSSigner.java#L197) ), but in the SprayAwsClient the encoded formData is never presented to the signer, which should leave the parameters unsigned.

I didn't verify this yet, since I don't have a post request with parameters in the S3Client.

**Comment by sclasen** [comment]
Hi @slomo ,  the signing itself just uses all the in-built aws stuff.  

https://github.com/sclasen/spray-aws/blob/master/spray-aws/src/main/scala/com/sclasen/spray/aws/SprayAWSClient.scala#L105 is all classes from the aws sdk.

So the trick is to make spray emit the same request as the aws sdk would have sent.  

A good way to do this (and something I had to do to get this approach working at the beginning) is to capture/catch the request in a debugger and see what it looked like, then fiddle around with the spray request until it matched. Once the requests match, the signature should as well.
